version: 1
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    verbose:
        format: "%(levelname)-8s %(asctime)s %(name)s %(filename)s:%(lineno)s | %(funcName) | %(message)s"
    very_verbose:
        format: "%(levelname)-8s %(asctime)s %(name)s %(pathname)s:%(lineno)s | %(funcName) | %(message)s"
handlers:
    console:
        class: logging.StreamHandler
        formatter: simple
        level: WARN
        stream: ext://sys.stderr
    file_debug:
        class: logging.handlers.RotatingFileHandler
        formatter: very_verbose
        level: DEBUG
        filename: /tmp/LOGGER_NAME_NOT_SET.debug.log
        maxBytes: 10485760
        backupCount: 3
    file_info:
        class: logging.handlers.RotatingFileHandler
        formatter: simple
        level: INFO
        filename: /tmp/LOGGER_NAME_NOT_SET.info.log
        maxBytes: 10485760
        backupCount: 3
    file_error:
        class: logging.handlers.RotatingFileHandler
        formatter: verbose
        level: ERROR
        filename: /tmp/LOGGER_NAME_NOT_SET.error.log
        maxBytes: 10485760
        backupCount: 3

root:
    level: DEBUG
    handlers: [console, file_info, file_error, file_debug]